let S={p:"all",c:"US",q:"",sale:false,sort:"featured",user:null};const $=x=>document.querySelector(x);
async function api(u,o={}){let r=await fetch(u,{...o,headers:{"Content-Type":"application/json",...(o.headers||{})}}),j=await r.json();if(!r.ok)throw Error(j.error||"Request failed");return j}
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function card(g){let money=g.free?"Free":new Intl.NumberFormat(undefined,{style:"currency",currency:g.currency||"USD"}).format(g.price);let old=g.regularPrice&&g.discount?new Intl.NumberFormat(undefined,{style:"currency",currency:g.currency||"USD"}).format(g.regularPrice):"";return `<article class="card"><div class="cover">${g.image?`<img loading="lazy" src="${g.image}" alt="">`:`<div class="placeholder">${esc(g.title)}</div>`}</div><div class="body"><div class="title">${esc(g.title)}</div><div class="meta"><span>${esc(g.platform)}</span><span>${g.country}</span></div><div class="price">${money}</div>${old?`<span class="old">${old}</span> <span class="sale">-${g.discount}%</span>`:""}<div class="source">${g.source==="live"?"LIVE PRICE":"DEMO DATA"}${g.url?` · <a target="_blank" href="${g.url}" style="color:#9a82ff">Store</a>`:""}</div></div></article>`}
async function games(){let p=new URLSearchParams({platform:S.p,country:S.c,q:S.q,sale:S.sale?"1":"0",sort:S.sort});$("#grid").innerHTML="<p>Loading games…</p>";try{let a=await api("/api/games?"+p);$("#grid").innerHTML=a.map(card).join("")||"<p>No games matched.</p>";$("#heading").textContent=S.q?`Results for “${esc(S.q)}”`:"Games";$("#info").textContent=`${a.length} shown · cached up to 24h`}catch(e){$("#grid").innerHTML=`<p class="err">${esc(e.message)}</p>`}}
async function status(){try{let s=await api("/api/status");$("#count").textContent=s.steamCatalogCount?Number(s.steamCatalogCount).toLocaleString():"Loading…"}catch{}}
async function me(){let x=await api("/api/me");S.user=x.user;$("#acct").innerHTML=x.user?`<span style="color:#98a2b2">Hi, ${esc(x.user)}</span><button id="logout">Log out</button>`:`<button id="login">Log in</button><button id="register" class="accent">Create account</button>`;$("#logout")?.addEventListener("click",async()=>{await api("/api/logout",{method:"POST"});me()});$("#login")?.addEventListener("click",login);$("#register")?.addEventListener("click",register)}
function show(h){$("#modalbody").innerHTML=h;$("#modal").hidden=false}
function login(){show(`<h2>Log in</h2><form id="form"><input id="un" placeholder="Username" required><input id="pw" type="password" placeholder="Password" required><button class="accent">Log in</button><p id="msg"></p></form>`)}
function register(){show(`<h2>Create account</h2><form id="form"><input id="un" placeholder="Username" required><input id="pw" type="password" placeholder="Password (6+ characters)" minlength="6" required><button class="accent">Create account</button><p id="msg"></p></form>`)}
async function reviews(){let a=await api("/api/reviews");$("#reviews").innerHTML=a.length?a.map(r=>`<div class="review"><div class="reviewtop"><b>${esc(r.title)}</b><span class="stars">${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</span></div><div>${esc(r.text)}</div><div class="reviewmeta">by ${esc(r.username)} · ${esc(r.platform)} · ${new Date(r.createdAt).toLocaleDateString()}</div></div>`).join(""):"<p style='color:#98a2b2'>No reviews yet.</p>"}
$("#close").onclick=()=>$("#modal").hidden=true;$("#platforms").onclick=e=>{if(e.target.dataset.p){document.querySelectorAll("#platforms button").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");S.p=e.target.dataset.p.toLowerCase();games()}};$("#country").onchange=e=>{S.c=e.target.value;games()};$("#sale").onchange=e=>{S.sale=e.target.checked;games()};$("#sort").onchange=e=>{S.sort=e.target.value;games()};$("#go").onclick=()=>{S.q=$("#q").value.trim();games()};$("#q").onkeydown=e=>{if(e.key==="Enter"){S.q=e.target.value.trim();games()}};
$("#modal").addEventListener("submit",async e=>{e.preventDefault();try{if(e.target.id==="form"){let registerMode=$("#modalbody").innerHTML.includes("Create account");await api(registerMode?"/api/register":"/api/login",{method:"POST",body:JSON.stringify({username:$("#un").value,password:$("#pw").value})});$("#modal").hidden=true;me()}else if(e.target.id==="reviewform"){await api("/api/reviews",{method:"POST",body:JSON.stringify({title:$("#rt").value,platform:$("#rp").value,rating:+$("#rr").value,text:$("#rx").value})});$("#modal").hidden=true;reviews()}}catch(err){$("#msg").textContent=err.message;$("#msg").className="err"}});
$("#review").onclick=()=>{if(!S.user)return login();show(`<h2>Write a review</h2><form id="reviewform"><input id="rt" placeholder="Game title" required><select id="rp"><option>Steam</option><option>Xbox</option><option>Nintendo</option><option>PlayStation</option><option>Meta Quest</option></select><select id="rr"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea id="rx" placeholder="Your review" required></textarea><button class="accent">Post review</button><p id="msg"></p></form>`)};me();status();games();reviews();
document.addEventListener("click", e => {
  const card = e.target.closest(".card");
  if (!card) return;
  const url = card.dataset.url;
  if (url && url !== "#") window.open(url, "_blank", "noopener,noreferrer");
});
